name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  build-update:
    runs-on: self-hosted
    steps:
      - run: npm install
      - run: npx eas update --channel preview --message "${{github.event.head_commit.message}}"
